name: Build and Deploy

on:
  push:
    branches:
      - binders-keep-style

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.15' # Specify your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to build branch
      env:
          PAT_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout -b build
        mv dist/* .
        git add .
        git commit -m "Build artifacts"
        git push origin build
